# tasks file for hostname
---
- name: update the hostname - hostname module
  hostname:
    name: "{{ inventory_hostname_short }}"
  tags: [configuration, hostname]

- name: update the hostname - /etc/hostname file
  template:
    src: etc/hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  tags: [configuration, hostname]

- name: update the hostname - /etc/hosts file
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags: [configuration, hostname]
